#!/bin/bash

# Install pre-requisites
#	yum install python-pip -y
#	pip install boto3 botocore PrettyTable

# Install the packages

#Get the installation directory from user
read -p "Where do you want to install(For example: /opt/aws-tool): " install_dir
mkdir -p $install_dir
if [ -d $install_dir ]; then
	echo "Installing the packages..."
	cp -rf ./packages/* $install_dir
fi


# Create Symlink
echo "Creating symlink..."
ln -sf $install_dir/aws-s3-cli.py /usr/bin/aws-s3-cli

echo "Installation completed!"


